### ISSUE TITLE
The library doesn't actually check the number of zero bits

### ISSUE THREAD

**Issue by ptrcnull** [catalinc/hashcash#2]
https://github.com/catalinc/hashcash/blob/e6bc29ff4de927cdd8143d58e119b6ba2735e8a4/hashcash.go#L32

this is wrong when given a number of bits that's not divisible by 4

**Comment by catalinc** [comment]
Hey, thanks for reporting this. I'm not actively maintaining this library. If you have a fix please open a PR and I'll take a look.
